"""empty message

Revision ID: c13de1d5699f
Revises: 
Create Date: 2023-03-03 01:24:58.021385

"""
from alembic import op
import sqlalchemy as sa
from models import *


# revision identifiers, used by Alembic.
revision = 'c13de1d5699f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('genres', sa.String(length=120), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('seeking_venue', sa.Boolean(), nullable=True),
    sa.Column('seeking_description', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('genres', sa.String(length=120), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('seeking_talent', sa.Boolean(), nullable=True),
    sa.Column('seeking_description', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Show',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'venue_id', 'start_time')
    )
    
    # Seed data
    fyyur_data = [
        sa.insert(Venue).values(
            id= 1,
            name= "The Musical Hop",
            genres= "Jazz,Reggae,Swing,Classical,Folk",
            address= "1015 Folsom Street",
            city= "San Francisco",
            state= "CA",
            phone= "123-123-1234",
            website= "https://www.themusicalhop.com",
            facebook_link= "https://www.facebook.com/TheMusicalHop",
            seeking_talent= True,
            seeking_description= "We are on the lookout for a local artist to play every two weeks. Please call us.",
            image_link= "https://images.unsplash.com/photo-1543900694-133f37abaaa5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60"
        ),
        sa.insert(Venue).values(
            id= 2,
            name= "The Dueling Pianos Bar",
            genres= "Classical,R&B,Hip-Hop",
            address= "335 Delancey Street",
            city= "New York",
            state= "NY",
            phone= "914-003-1132",
            website= "https://www.theduelingpianos.com",
            facebook_link= "https://www.facebook.com/theduelingpianos",
            seeking_talent= False,
            image_link= "https://images.unsplash.com/photo-1497032205916-ac775f0649ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80"
        ),
        sa.insert(Venue).values(
            id= 3,
            name= "Park Square Live Music & Coffee",
            genres= "Rock n Roll,Jazz,Classical,Folk",
            address= "34 Whiskey Moore Ave",
            city= "San Francisco",
            state= "CA",
            phone= "415-000-1234",
            website= "https://www.parksquarelivemusicandcoffee.com",
            facebook_link= "https://www.facebook.com/ParkSquareLiveMusicAndCoffee",
            seeking_talent= False,
            image_link= "https://images.unsplash.com/photo-1485686531765-ba63b07845a7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=747&q=80"
        ),
        sa.insert(Artist).values(
            id= 4,
            name= "Guns N Petals",
            genres= "Rock n Roll",
            city= "San Francisco",
            state= "CA",
            phone= "326-123-5000",
            website= "https://www.gunsnpetalsband.com",
            facebook_link= "https://www.facebook.com/GunsNPetals",
            seeking_venue= True,
            seeking_description= "Looking for shows to perform at in the San Francisco Bay Area!",
            image_link= "https://images.unsplash.com/photo-1549213783-8284d0336c4f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80"          
        ),
        sa.insert(Artist).values(
            id= 5,
            name= "Matt Quevedo",
            genres= "Jazz",
            city= "New York",
            state= "NY",
            phone= "300-400-5000",
            facebook_link= "https://www.facebook.com/mattquevedo923251523",
            seeking_venue= False,
            image_link= "https://images.unsplash.com/photo-1495223153807-b916f75de8c5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80"
        ),
        sa.insert(Artist).values(
            id= 6,
            name= "The Wild Sax Band",
            genres= "Jazz,Classical",
            city= "San Francisco",
            state= "CA",
            phone= "432-325-5432",
            seeking_venue= False,
            image_link= "https://images.unsplash.com/photo-1558369981-f9ca78462e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=794&q=80"
        ),
        sa.insert(Show).values(
            artist_id=4,
            venue_id=1,
            start_time="2019-05-21T21:30:00.000Z"
        ),
        sa.insert(Show).values(
            artist_id=5,
            venue_id=3,
            start_time="2019-06-15T23:00:00.000Z"
        ),        
        sa.insert(Show).values(
            artist_id=6,
            venue_id=3,
            start_time="2035-04-01T20:00:00.000Z"
        ),
        sa.insert(Show).values(
            artist_id=6,
            venue_id=3,
            start_time="2035-04-08T20:00:00.000Z"
        ),
        sa.insert(Show).values(
            artist_id=6,
            venue_id=3,
            start_time="2035-04-15T20:00:00.000Z"
        )        
        ]    
    
    for stmt in fyyur_data:
        op.execute(stmt)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    op.drop_table('Venue')
    op.drop_table('Artist')
    # ### end Alembic commands ###
